### ISSUE TITLE
Add Load Balancer Convey

### ISSUE THREAD

**Issue by naomijub** [rust-unofficial/awesome-rust#1003]
Convey https://github.com/bparli/convey is a layer 4 Load Balancer and in its early stages has outperformed nginx and HAProxy. I would add it to  [**Cloud**](https://github.com/rust-unofficial/awesome-rust#cloud) or create a new field **Load Balancer**.

Thank you

**Comment by palfrey** [comment]
Can you submit a PR for this please?

**Comment by naomijub** [comment]
https://github.com/rust-unofficial/awesome-rust/pull/1134

**Comment by palfrey** [comment]
https://github.com/rust-unofficial/awesome-rust/pull/1134 now merged
