### ISSUE TITLE
Add SmartCore to Artificial Intelligence / Machine Learning

### ISSUE THREAD

**Issue by vsonicmu** [rust-unofficial/awesome-rust#1054]
Can SmartCore please be added to the list of Machine Learning libraries? It is a meta-library (similar in concept to linfa)

**Crate**: https://crates.io/crates/smartcore
**Homepage**: https://smartcorelib.org/
**Github**: https://github.com/smartcorelib/smartcore

thank you!

**Comment by palfrey** [comment]
Can you submit a PR for this please?
