### ISSUE TITLE
Some UI/Frontend Libraries

### ISSUE THREAD

**Issue by philip-peterson** [rust-unofficial/awesome-rust#1076]
The following may make a valuable addition to the UI/frontend frameworks and tools lists:

* [Percy](https://github.com/chinedufn/percy) -- 1600 stars
* [Trunk](https://github.com/thedodd/trunk) -- 446 stars
* [Maple](https://github.com/lukechu10/maple) -- 155 stars

**Comment by pytogata** [comment]
Горячий 
--
Отправлено из Mail.ru для Android среда, 28 апреля 2021г., 08:46 +03:00 от Philip Peterson  ***@***.*** :

**Comment by palfrey** [comment]
Can you submit a PR for these please?

**Comment by palfrey** [comment]
Closing as there's no PR been made, and this is quite old
