### ISSUE TITLE
ytop no longer maintained

### ISSUE THREAD

**Issue by JoelMon** [rust-unofficial/awesome-rust#1087]
The System Tools > [ytop](https://github.com/cjbassi/ytop) project is no longer maintained. They refference another similar project, [bottom](https://github.com/ClementTsang/bottom).

**Comment by palfrey** [comment]
Could you submit a PR please removing ytop and adding bottom?

**Comment by JoelMon** [comment]
> Could you submit a PR please removing ytop and adding bottom?

Will do!
