### ISSUE TITLE
Add `rumqtt`

### ISSUE THREAD

**Issue by de-sh** [rust-unofficial/awesome-rust#1267]
Hey there folks, I'd like to add [`rumqtt`](https://github.com/bytebeamio/rumqtt), a library for writing applications that use the [MQTT](https://mqtt.org/) protocol to communicate.

**Comment by palfrey** [comment]
Please submit a PR adding it to the list!

**Comment by de-sh** [comment]
I'd also like for [mquictt/mquictt](https://github.com/mquictt/mquictt) to be added to this PR, but it is experimental and **VERY VERY ALPHA** to say the least 😅
