### ISSUE TITLE
Link to Soloud Rust project removed

### ISSUE THREAD

**Issue by MoAlyousef** [rust-unofficial/awesome-rust#1350]
Hello

The previously added soloud project in PR https://github.com/rust-unofficial/awesome-rust/pull/946 seems to have disappeared for some reason.

**Comment by palfrey** [comment]
Yes. It got removed during https://github.com/rust-unofficial/awesome-rust/pull/1141 when popularity filtering ("you need at least 50 stars or 2000 downloads") got implemented. It now appears to have enough downloads, so a PR re-adding it would be accepted.
