### ISSUE TITLE
Replace discontinued editors in favour of the successors

### ISSUE THREAD

**Issue by joergdw** [rust-unofficial/awesome-rust#1402]
The follwing replacements in the [Text-Editors](https://github.com/rust-unofficial/awesome-rust#text-editors) section could be made due to the project's discontinuations:
- [xi-editory](https://github.com/xi-editor/xi-editor) by [Lapce](https://github.com/lapce/lapce)
- [remacs](https://github.com/remacs/remacs) by [emacs-ng](https://github.com/emacs-ng/emacs-ng)

Similiarly for [GUI libraries](https://github.com/rust-unofficial/awesome-rust#gui):
- [druid](https://github.com/linebender/druid) by [xilem](https://github.com/linebender/xilem)

**Comment by palfrey** [comment]
Thanks for reporting this. Can you submit a PR please fixing these?

**Comment by joergdw** [comment]
https://github.com/rust-unofficial/awesome-rust/pull/1403
