### ISSUE TITLE
vs codium in the list? 

### ISSUE THREAD

**Issue by slayernominee** [rust-unofficial/awesome-rust#1422]
you could add vs codium in the ide list i think

**Comment by palfrey** [comment]
Not seeing any rust bits in https://github.com/VSCodium/vscodium ?

**Comment by slayernominee** [comment]
yes, but the vscode is also in the list because of the extension it has ... so I thought it would be a good idea to also add vscodium since it also can use the rust extension and since its by default without the telemetry I would prefer it over vscode 🤔

**Comment by Israel-Laguan** [comment]
In that case maybe substituting vscode?

**Comment by slayernominee** [comment]
it would be my favorite solution

**Comment by palfrey** [comment]
No, for several reasons:
1) Neither of them are Rust projects, and so the only reason to link is so people can find the plugins. I'm fairly sure _every_ vs codium user knows about vscode and not necessarily vice versa, so this would reduce the usability of the list.
2) I'm not sure every plugin we've got listed works with vs codium. Probably? Depends on what they cut out right now. I'm much more sure they all work with vscode. I really don't want to be in the business of having to remember to only allow vs codium compliant plugins in the future, as that makes maintenance harder.
