### ISSUE TITLE
Add `sysexits` crate

### ISSUE THREAD

**Issue by sorairolake** [rust-unofficial/awesome-rust#1433]
I'd like to add [`sysexits`](https://crates.io/crates/sysexits), a library that provides the system exit code constants as defined by [`<sysexits.h>`](https://man.openbsd.org/sysexits). It has been downloaded over 2,000 times on crates.io. But, I don't know which section to add it to. Which section should I add it to?

**Comment by palfrey** [comment]
[Libraries/System](https://github.com/rust-unofficial/awesome-rust#system) seems the best match for this.

**Comment by sorairolake** [comment]
@palfrey Thanks!
