### ISSUE TITLE
Potentially remove or deprecate rustbuster from the security tools list

### ISSUE THREAD

**Issue by lavafroth** [rust-unofficial/awesome-rust#1491]
Hi, the [rustbuster project](https://github.com/phra/rustbuster) under the [security tools](https://github.com/rust-unofficial/awesome-rust/issues/new) is no longer actively maintained, its last commit being on 27th October, 2021.

Furthermore, if you try to build and run the tool from its latest commit, it panics and crashes, refer to this issue: https://github.com/phra/rustbuster/issues/49

Thus, I suggest either removing the tool from the list or adding some kind of deprecated flag next to it.

**Comment by palfrey** [comment]
I've just been experimenting with it (see https://github.com/phra/rustbuster/issues/53) and yeah, it's very broken, so I've removed it in 2192f33986e8c895c0f839680cf5cfb4cff10502.
