### ISSUE TITLE
flutter-rs/flutter-rs is no updates since 2020

### ISSUE THREAD

**Issue by erlangparasu** [rust-unofficial/awesome-rust#1604]
flutter-rs/flutter-rs is no updates since 2020

**Comment by palfrey** [comment]
As per the [contributing guide](https://github.com/rust-unofficial/awesome-rust/blob/main/CONTRIBUTING.md) "We don't remove projects unless they are outright broken or pronounced deprecated by another project or by its author."

I'm not seeing a successor project. I'm seeing a variety of "please use X which is well maintained", and some bugs, but nothing to indicate it's totally borked.

**Comment by erlangparasu** [comment]
oh sorry, thanks for the information
