### ISSUE TITLE
Fix build #3 by correct errors found by awesomebot

### ISSUE THREAD

**Issue by booyaa** [rust-unofficial/awesome-rust#309]
https://travis-ci.org/rust-unofficial/awesome-rust/builds/244830080

We shouldn't normally need to do this with future pull requests, now that we've enabled on travis.

I would also make the suggestion that all maintainers should start using PR rather than editing the file directly so we can all utilise awesomebot validation via travis.

cc @kud1ing @Manishearth @luciusmagn @Freyskeyd

**Comment by kud1ing** [comment]
Regarding the 4040 from creates.io i've opened https://github.com/rust-lang/crates.io/issues/788

I think PRs are not necessary for Travis. The commit which triggered https://travis-ci.org/rust-unofficial/awesome-rust/builds/244830080 was not done via a PR.

**Comment by kud1ing** [comment]
Passes, thanks.

**Comment by LahyanDjeh** [comment]
Edit on my git project profile
