### ISSUE TITLE
have a data processing category? to include the weld-project from standford

### ISSUE THREAD

**Issue by c0b** [rust-unofficial/awesome-rust#330]
- https://github.com/weld-project/weld
- http://weld.stanford.edu/ redirect to https://weld-project.github.io/

it's written in Rust and main use cases are in Big Data Processing

**Comment by kud1ing** [comment]
Yes, that makes sense. If you can, please submit a pull request.

We have "graph processing" already and i think it could be moved as a sub catagory of the new category.

**Comment by luciusmagn** [comment]
Hello @c0b, are you still interested in adding these crates?
