### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by cardoe** [rust-unofficial/awesome-rust#331]
Please consider the following crates:

- pem For parsing data from PEM files
- cargo-ebuild For creating Gentoo ebuilds from crates.io packages
- cargo-bitbake For creating Yocto recipes from crates.io packages

**Comment by luciusmagn** [comment]
Sure, looks pretty nice. You can certainly open a PR for your crates, just follow the standard format for entries

**Comment by luciusmagn** [comment]
@cardoe are you still interested in adding these crates?

**Comment by cardoe** [comment]
Yes. Apologies. This slipped through the mental cracks.

**Comment by luciusmagn** [comment]
Thanks, merged
