### ISSUE TITLE
Consider removing scirust

### ISSUE THREAD

**Issue by stiv-yakovenko** [rust-unofficial/awesome-rust#333]
It doesn't build nowdays and doesn't seem to be supported any more...

**Comment by kud1ing** [comment]
I agree that removing can be as important as adding.
In this case however i think the time has not come yet. The project builds for me (Rust 1.20) and to me inactivity begins (subjectively) after about 1-2 years.
Thanks for the hint anyway.

**Comment by luciusmagn** [comment]
Builds for me too, do you maybe mean the build.txt file in the respository? That one shows failure, but only because some tests failed. However, the file is 2 years old, so it's probably not relevant anymore
