### ISSUE TITLE
Add `zap`

### ISSUE THREAD

**Issue by oldaniel** [rust-unofficial/awesome-rust#348]
`zap` is a lightning fast web framework that is up to **2.8times faster** than iron which is based on hyper.

Currently the `0.0.1` release had been done, and there will come a lot of future add-ons and optimizations to reach the 3times faster mark.

URL: https://github.com/oldaniel/zap

**Comment by luciusmagn** [comment]
Thanks, looks very interesting, I'll quickly add it. Next time you can just open a pull request directly :)

**Comment by oldaniel** [comment]
@luciusmagn Ok, will do it the next time.

**Comment by oldaniel** [comment]
@luciusmagn Zap isn't a Websocket Libary. Just a HTTP server like iron

**Comment by luciusmagn** [comment]
Oh yeah, my bad
