### ISSUE TITLE
Consider removing JustSid/AfterglowIntelliJ 

### ISSUE THREAD

**Issue by Kendos-Kenlen** [rust-unofficial/awesome-rust#353]
The IntelliJ plugin JustSid/AfterglowIntelliJ has nothing to do with Rust programming, and is not even written in Rust. It should be removed from this list.
It is rather a theme for IntelliJ and the only thing it comes with regarding rust is a file icon ...

**Comment by kud1ing** [comment]
I agree, thank you.

https://github.com/rust-unofficial/awesome-rust/commit/d6f217a01fdecffa716a55c58e2b45fa487234c2
