### ISSUE TITLE
Split categories in to files?

### ISSUE THREAD

**Issue by Luke-Nukem** [rust-unofficial/awesome-rust#382]
Wondering if it would be a good idea to split categories in to separate md files?

Reason being, it may become harder to keep track and/or edit later.

**Comment by luciusmagn** [comment]
This idea might sound good on paper, but I see several pitfalls:

- Many files might be created, which could introduce mess
- Automatic validation using Travis w/ awesome-bot would be more complicated
- Searching in the list would be harder, right now it's just Ctrl+F for whole list
- Less 'versatile' - right now, I can just use a simple script to have a render of the list on my website http://magnusi.tech/awrs for testing purposes. Splitting it takes this away
- Ambiguity - should each sub-category of Development Tools have own file, or all of them in one file? If all dev tools would be in one file, Libraries should systematically be in only one file, too, ultimately defeating the purpose splitting it

So far, we keep track line-by-line. Of course, there are pros of multiple files too, but I believe they are outweighed by the cons right now. Maybe in the future.

Would you like to add anything, @kud1ing?

**Comment by kud1ing** [comment]
I agree with @luciusmagn especially regarding maintenance, browsability and searchability.
I'd like to postpone that until the pain of not doing is gets overwhelming,

**Comment by Luke-Nukem** [comment]
I think I agree in the end too. Maybe some time in the future it will need to be revisited, but not now eh?

I'll close.
