### ISSUE TITLE
Add "trust"

### ISSUE THREAD

**Issue by amilajack** [rust-unofficial/awesome-rust#389]
[trust](https://github.com/japaric/trust) is a "Travis CI and AppVeyor template to test your Rust crate on 5 architectures and publish binary releases of it for Linux, macOS and Windows"

Would a PR for this be welcome?

**Comment by luciusmagn** [comment]
It most certainly would. Feel free to open it.

2017-12-12 20:36 GMT+01:00 Amila Welihinda <notifications@github.com>:
