### ISSUE TITLE
Industrial automation category?

### ISSUE THREAD

**Issue by flosse** [rust-unofficial/awesome-rust#404]
I'd like to add the [tokio-modbus](https://github.com/slowtec/tokio-modbus)  library but I'm missing an appropriate category. Would you accept `Industrial automation` or `Automation engineering`?

**Comment by luciusmagn** [comment]
Industrial Automation sounds good, although probably both would be fine. Sorry I missed this issue for so long

**Comment by flosse** [comment]
Thanks for your feedback. I just crated #444 :)
