### ISSUE TITLE
Cebuano Localization

### ISSUE THREAD

**Issue by jbeguna04** [rust-unofficial/awesome-rust#430]
Hi Good Day! I would like to request to contribute in your project. Please allow me to have translation in Cebuano. Hoping for your positive response!
Thank You!

**Comment by luciusmagn** [comment]
Howdy, the project is licensed under CC0, so I don't think there is anything stopping you from having your own translation in whatever language you desire. It would probably be nice to mention us in there somewhere, though. Best of luck,
Lukáš

**Comment by luciusmagn** [comment]
Unless there is something you would like to add, I will be closing this issue for now. Good luck.
