### ISSUE TITLE
Feature: add nebulet to Operating Systems

### ISSUE THREAD

**Issue by dbkaplun** [rust-unofficial/awesome-rust#463]
https://github.com/rust-unofficial/awesome-rust#operating-systems
https://github.com/nebulet/nebulet

Thanks!

**Comment by luciusmagn** [comment]
Ah, sorry, missed the issue :sweat_smile:
Nebulet looks mighty fine and would be a great addition to the list. You can open a PR to add it, if you want (that is the standard procedure for proposing new entries), or I can add it, if you aren't up for the task.
