### ISSUE TITLE
Can't install toolchain

### ISSUE THREAD

**Issue by Raj2032** [rust-unofficial/awesome-rust#482]
For some reason when I installed Rust (rls), it prompted me to install toolchain so I did now I get this error

https://discourse-cdn-sjc1.com/business5/uploads/rust_lang/original/2X/d/d1d55e667511d5538b141de83b203327d8178c3c.png

May I know how to resolve this?

**Comment by Raj2032** [comment]
I accidently closed the other issue so I made a new issue

**Comment by brycx** [comment]
I think you're looking for [RLS](https://github.com/rust-lang-nursery/rls).

**Comment by luciusmagn** [comment]
For future reference, you can reopen the issues that you close, there is a button for that :smiley: 

We are mostly just about collecting cool projects and not really a help central, but I suggest checking out the link in @brycx's comment. RLS stands for Rust Language Server and is not the same as just Rust. The recommended way to install Rust is to use <rustup.rs> which has an installer for all the major platforms.

Feel free to respond here if you have any further problems.
