### ISSUE TITLE
Anything about GraphQL?

### ISSUE THREAD

**Issue by frederikhors** [rust-unofficial/awesome-rust#698]
Anything about GraphQL?

**Comment by luciusmagn** [comment]
Well, I have heard about several liberaries.

Namely:

- [Juniper](https://github.com/graphql-rust/juniper)
- [graphql](https://github.com/nrc/graphql)

GraphQL support in Rust isn't 100% mature, but it's already starting to look promising!

**Comment by h-michael** [comment]
client library: https://github.com/graphql-rust/graphql-client

**Comment by palfrey** [comment]
graphql-client and Juniper are now both linked. @luciusmagn Can I close this?
