### ISSUE TITLE
Please incorporate posts from this beautilful Reddit thread in /r/rust

### ISSUE THREAD

**Issue by igor-petruk** [rust-unofficial/awesome-rust#715]
https://www.reddit.com/r/rust/comments/cysvjh/what_are_some_amazing_softwaresoftware_clones/

It helped me to discover things like starship, hors, dust, missing from this list.

**Comment by palfrey** [comment]
If you can go through and submit PRs for anyone of those, that would be appreciated!

**Comment by palfrey** [comment]
Closing as this has been open for 8 months, and no PR. Please re-open if you want to submit a PR for this.
