### ISSUE TITLE
Do we want to add live streamers or YouTube playlists?

### ISSUE THREAD

**Issue by BrooksPatton** [rust-unofficial/awesome-rust#729]
I have enjoyed watching some YouTube playlists as well as live streamers who are using Rust. Would links to the playlists or streamer pages be something the community would b interested in adding?

**Comment by senden9** [comment]
Streamers can now be found under https://github.com/jamesmunns/awesome-rust-streaming

**Comment by palfrey** [comment]
If you want to add a PR adding that link to the README, that would be appreciated :)
