### ISSUE TITLE
Can you add Bastion ecosystem?

### ISSUE THREAD

**Issue by vertexclique** [rust-unofficial/awesome-rust#783]
Can you add:
* [Bastion](https://github.com/bastion-rs/bastion): Erlang like highly-available fault-tolerant runtime
* [Artillery](https://github.com/bastion-rs/artillery): Distributed carrier protocol for Bastion
* [Numanji](https://github.com/bastion-rs/numanji): Local-affinity first NUMA-aware allocator with optional fallback.

**Comment by palfrey** [comment]
Could you submit a PR for this please? We'd be interested in the entries.

**Comment by palfrey** [comment]
Closing for the moment as no response to previous query. Feel free to submit the PR later on though!
