### ISSUE TITLE
Can you add Cuneiform crates?

### ISSUE THREAD

**Issue by vertexclique** [rust-unofficial/awesome-rust#784]
[Cuneiform](https://github.com/vertexclique/cuneiform): Cache optimizations for Rust. (no_std)
[Cuneiform Fields](https://github.com/vertexclique/cuneiform-fields): Field level cache optimizations for Rust. (no_std)

**Comment by palfrey** [comment]
> [Cuneiform](https://github.com/vertexclique/cuneiform): Cache optimizations for Rust. (no_std)
> [Cuneiform Fields](https://github.com/vertexclique/cuneiform-fields): Field level cache optimizations for Rust. (no_std)

Please submit a PR and we'll have a look!

**Comment by palfrey** [comment]
Closing as this has been open for 4 months, and no PR. Please re-open if you want to submit a PR for this.
