### ISSUE TITLE
'Actor' Crates

### ISSUE THREAD

**Issue by ZempTime** [rust-unofficial/awesome-rust#824]
I've been evaluating crates for use as the basis of an actor-based system.

One of the top contenders, https://github.com/riker-rs/riker , isn't on this list.

* riker-rs/riker — An Akka-inspired Actor library for Rust

Where should this go on the list? (Inside the 'Low-level' section?) Does this deserve a category?

Let me know what you think, and I'll PR it in

**Comment by palfrey** [comment]
"Low-level" seems the best of our existing categories, but that possibly needs some refactoring.

@luciusmagn Any thoughts on this?

**Comment by palfrey** [comment]
Closing this issue as there hasn't been a PR made for it, and it's pretty old!
