### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by rugk** [rust-unofficial/awesome-rust#834]
Your Travis build https://travis-ci.org/rust-unofficial/awesome-rust is fasiling with the link https://www.manning.com/livevideo/rust-in-motion?a_aid=cnichols&a_bid=6a993c2e

**Comment by palfrey** [comment]
Hmm. Looks like a transient failure of that site, despite our attempts at retries. I've just re-run the build, and it's looking fine again. We might however at some point need to look at caching results for an extended period of time to further workaround items like this.
