### ISSUE TITLE
Add https://github.com/Edu4rdSHL/findomain to Security Tools

### ISSUE THREAD

**Issue by chevonmdphillip** [rust-unofficial/awesome-rust#861]
Hi,

This is more off a request. Can you please add https://github.com/Edu4rdSHL/findomain to your security tools section.

**Comment by palfrey** [comment]
> This is more off a request. Can you please add https://github.com/Edu4rdSHL/findomain to your security tools section.

Please submit a PR and we'll have a look at it. Thanks!
