### ISSUE TITLE
WebAssembly section

### ISSUE THREAD

**Issue by OAyomide** [rust-unofficial/awesome-rust#869]
Can we have a WASM section? I know some things like wain are in categories like FFI but it would be nice to have a dedicated WASM category containing WASM stuff only. 

@palfrey thoughts?

**Comment by Z-M-I-T-H** [comment]
Well, there's web frontend section. I would recommend also [woz.sh](woz.sh).

**Comment by palfrey** [comment]
For the moment they should still go under the FFI / Web Assembly section. If that bit gets large enough, then we can split it out.

**Comment by palfrey** [comment]
Closing, as the original issue got resolved by flagging a section
