### ISSUE TITLE
Add an error handling section

### ISSUE THREAD

**Issue by yaahc** [rust-unofficial/awesome-rust#899]
I'm planning on doing this myself with a PR but I figured I'd open a discussion first to verify that there isn't any particular reason there's not already an error handling section and to get the maintainers opinions about how such a section should be structured.

My plan is to add a section on error handling that then has sub sections by error handling sub problems, and then list libraries in each sub section that best describes their primary purpose.

Something like this, though more detailed:

---

### Error Construction Libraries

* thiserror - derive macro for implementing the `Error` and `Display` traits for structs and enums.
* snafu - derive macro for implementing the `Error` and `Display` traits on structs and enums with helpers for wrapping errors and capturing backtraces
etc...

### Error Reporting Libraries

* anyhow - 
* eyre -
etc...

### Error Utility Libraries

* errtools - helpful extensions for error types such as serialization / deserialization and downcasting over a chain of errors
* tracing-error - backtrace-like type for instrumenting errors with `tracing` span information
* fehler - proc macro for exception like semantics and ok wrapping in rust functions

----

There's definitely a lot of overlap, for example eyre and anyhow also provide a lot of helpers for constructing errors, but I think in general breaking up the main use cases for these libraries will make a huge difference in helping rust developers figure out which libraries they should be using, and i think `awesome-rust` is the ideal place to share this information.

**Comment by palfrey** [comment]
Sounds good to me. The main reason that we don't have an error library section so far is that no one submitted a PR :) The format sounds good, and note that in line with other sections that if there's a library that's actually "all of the above", then it could get put straight under "Error Handling" as opposed to needing to go under one of the subsections.

Thanks for the idea, and looking forwards to seeing the PR!

**Comment by palfrey** [comment]
Closing for the moment as no response to previous query. Feel free to submit the PR later on though!
