### ISSUE TITLE
Add minifb library

### ISSUE THREAD

**Issue by Chief-Detektor** [rust-unofficial/awesome-rust#931]
Hi!
While I was looking for some low level windowing/gfx libs here I was surprised that [minifb](https://github.com/emoon/rust_minifb) was not added, yet.
It's a cross platform library that provides the user basically with a framebuffer and keyboard and mouse input.
I am not sure under which category this would fit best (gfx, or a even a new category)?

Thanks for this awesome list!
Keep up the cool work!

**Comment by palfrey** [comment]
Looks interesting. Possibly under the GUI category? Please submit a PR to add it.

**Comment by palfrey** [comment]
Fixed in #976
