### ISSUE TITLE
rr does not use Rust

### ISSUE THREAD

**Issue by rocallahan** [rust-unofficial/awesome-rust#950]
Not sure why it's on your list.

**Comment by palfrey** [comment]
Hmm. Not sure why that got added (the original PR, #245 doesn't have any hints). I've removed it in eac69d67abb91a1ec5451e9fffc3a5ef7f2bfac6.

**Comment by luciusmagn** [comment]
If I recall correctly, nothing in the Debugging section was written in Rust (IIRC), but they were added because they had
support for Rust, hence counting as a Rust resource, not Rust code.

I don't know much about rr though

**Comment by rocallahan** [comment]
Oh, I see! Sorry!

After scrolling through hundreds of applications and tools written in Rust I just assumed everything on the list was supposed to be written in Rust. I didn't realize that it transitioned to tools that you can use to work with Rust. So I filed this bug in error, sorry.

**Comment by rocallahan** [comment]
It is certainly true that rr works with Rust.
