### ISSUE TITLE
Add zenoh

### ISSUE THREAD

**Issue by kydos** [rust-unofficial/awesome-rust#988]
[zenoh](https://crates.io/crates/zenoh) is an innovative communication framework entirely written in async Rust. We focus on the unification of data in motion and data at rest as such zenoh can be used as a pub/sub or a geo-distributed storage system.  

We propose to add zenoh to the network programming and the data-base sections of your list. We'll  submit a pull request with the suggested changes. 

Thanks!

**Comment by BinChengZhao** [comment]
I'm having the same problem, PR is reporting errors during the CI process, there seems to be a small problem with the official CI, hopefully this can be fixed.

**Comment by kydos** [comment]
Indeed @BinChengZhao, it seams that the build for the project is failing.

**Comment by kydos** [comment]
@luciusmagn, please let me know if there is anything else that needs to be done in order to get Zenoh on the list.
Thanks!

**Comment by palfrey** [comment]
The build has been fixed for a while now. Is there a PR for this?

**Comment by kydos** [comment]
I'll make one right off. Thanks!
